### ISSUE TITLE
Will you take pull requests with new replications?

### ISSUE THREAD

**Issue by jack-willturner** [sadielbartholomew/creative-matplotlib#1]
I love this project 😍

I was wondering if I could contribute some replications?

**Comment by sadielbartholomew** [comment]
Hi Jack, thanks very much for your kind comments and for raising this. It actually pre-empts my plans since I was thinking of advertising the repo for new contributions towards this year's 'Hacktoberfest' and trying to open it up more widely for general contributions from there. It is great if you are willing to create some replications of your own for the repo and be the first contributor other than myself! :smiley: 

I was going to put up some contributor guidelines nearer to October and maybe I can put them up sooner. Until then, in case you wanted to put up a PR soon, I would say the only basic requirements for any mini-project additions that I would accept are that:

* naturally, they come under the 'creative coding' umbrella and are generated with matplotlib as the main (or perhaps only? I'm not sure whether to be that strict) tool for visualisation;
* outputs are shared as well as the full code to generate at least some of them and/or some variation of them (if, say, randomness is involved so that each run would give a different result based on that).

So any PRs that satisfy those criteria would be very welcome!

Hopefully the organisation of the repo makes it clear what would be required for anything new, e.g. a new directory to hold a new mini-project with a sub-directory to hold the output images.

Were you thinking about adding replications to an existing mini-project listed on the root README, or to start a new one? Either is fine, though I ask because I would like to make it clear who has contributed what to the repo in the README galleries, for attribution etc., and it will be much easier to mark that in the latter case, where each mini-project is contributed by one person. In the former case I can have a think about how to indicate who created what outputs and with what form of the script, etc.

Otherwise, just let me know here if you have any questions relating to the repo or a potential PR and I look forward to seeing any code and outputs that you would like to contribute! Thanks again :100:

**Comment by sadielbartholomew** [comment]
(I've noted that I should write contributing guidelines soon in #2 to help me to remember to do that.)

**Comment by jack-willturner** [comment]
Cool! Thanks for the detailed response ☺️

> Were you thinking about adding replications to an existing mini-project listed on the root README, or to start a new one? 

I wanted to start with an Ellsworth Kelly painting called [Cité](https://ellsworthkelly.org/work/cite/)! 

Maybe for now I can just add it to the table with the others in the README of that mini-project, until you have decided on a good way to separate out attributions?

**Comment by sadielbartholomew** [comment]
Hi again @jack-willturner, sorry for the delay in getting back to you, I've been busy catching up with work so not had time to reply so far.

> I wanted to start with an Ellsworth Kelly painting called Cité!

I saw the PR go up and had a glance at the output already, it looks fantastic! It will be a wonderful addition to the project. The original is a very lovely piece, I think, too.

I'll start reviewing the PR, mostly just checking the new code generates something similar on my local environment without changing the outputs from that Ellsworth Kelly mini-project that were already produced,  now over lunch.

> Maybe for now I can just add it to the table with the others in the README of that mini-project, until you have decided on a good way to separate out attributions?

That's fine by me and I see that's how you've done it in the PR. Of course the version control shows who contributed what code to each script clearly, so maybe all that is required for attributions is to tag the outputs in the README gallery.

Anyway, I'll ask about that over on the PR. I think this Issue in itself can be closed because hopefully I've made it clear that contributions with new replications are very welcome and I will try to actively encourage them from anyone interested soon via adding contributing guidelines and advertising with labels etc. :slightly_smiling_face: Thanks for initiating this and being the first to contribute!
